import type { Metadata } from "next";
import { Montserrat } from "next/font/google";


import BootstrapClient from "@/lib/BootstrapClient";
import "bootstrap/dist/css/bootstrap.min.css";


const montserrat = Montserrat({ subsets: ["cyrillic"] });

export const metadata: Metadata = {
  title: "Spelling Bee Game",
  description: "Generated by NextJS",
};

interface RootLayoutProps {
  children: React.ReactNode;
  params: { locale: string };
}

export default function RootLayout({
  children,
  params: { locale },
}: Readonly<RootLayoutProps>) {
  return (
    <html lang={locale}>
      <body className={montserrat.className}>{children}
      <BootstrapClient />
      </body>
    </html>
  );
}
